mkdir --verbose intermediates
cd intermediates
mkdir --verbose cyclone_coordinates
mkdir --verbose db
mkdir --verbose detectnodes
mkdir --verbose era5
mkdir --verbose era5_mslp
mkdir --verbose seaice_concentrations
mkdir --verbose shapes
mkdir --verbose shapes/sentinel1
mkdir --verbose shapes/swot
mkdir --verbose swot
mkdir --verbose stitchnodes
mkdir --verbose te_out
mkdir --verbose tempestextreme_files
mkdir --verbose tempestextreme_files/logs
mkdir --verbose tiffs
mkdir --verbose uuids
mkdir --verbose dump
mkdir --verbose dump/sentinel1
mkdir --verbose dump/swot